# REPLACE

# app and org for use with dashboard.serverless.com
service: test
app: test
org: cgarrovillo
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  memorySize: 512
  region: us-west-2
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
    resourcePolicy:
      - Effect: Deny
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          NotIpAddress:
            aws:SourceIp:
              # Home IP
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*

  environment:
    # Sample Environment Variable from AWS parameter store
    SAMPLE_ENV: ${ssm:MONGODB_URI}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    noPrependStageInUrl: true

functions:
  app:
    handler: build/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy+}'
          method: ANY
